// <auto-generated />
using System;
using Api.Data;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Data
{
    [DbContext(typeof(RoomContext))]
    [Migration("20201110170921_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Api.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescribeNeighborhood")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialDeposit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSecurityChecked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layout")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MoveInDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberBathRooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberBedRooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberRoommateAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rent")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoommateDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpaceDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("StayDuration")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
